services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
