apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgress
  POSTGRES_USER: postgress
  POSTGRES_PASSWORD: postgress
  DATABASE_URL: "postgresql://postgres:postgres@localhost/base?schema=public"