apiVersion: v1
kind: Service
metadata:
  name: ms-user-service
  namespace: default
  labels:
    name: ms-user
    app: service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 4001
    targetPort: 4001
  externalIPs:
  - 192.168.49.2
  selector:
    app: ms-user
